### ISSUE TITLE
Exception in thread "main" org.json.JSONException: JSONObject["shards"] not found.

### ISSUE THREAD

**Issue by Hinkii** [Frederikam/FredBoat#122]
Hi, I'm having a problem starting the bot, running off Windows by the way, which I know isn't truly supported(?) Though it was working in a javaw environment, but I wanted it running it in java cmd prompt console environment. With a really old but the bot updated my config and credentials.yaml files it would flare up but never actually stopped the launch, but now with the most recent format it's not seeming to want to actually, "start." I'll link my config and credential files in this post.

-though I guess it'll be in .txt format for GitHub's pleasure. :v

[config.txt](https://github.com/Frederikam/FredBoat/files/879951/config.txt)
[credentials.txt](https://github.com/Frederikam/FredBoat/files/879950/credentials.txt)

**Comment by Frederikam** [comment]
FredBoat works fine on Windows, in fact, I use Windows to develop the bot.

This exception is thrown when your bot token is invalid. Make sure your bot token is valid, and that it isn't a user token.

**Comment by Hinkii** [comment]
Okay now it loads up but then I'm given the error:
javax.security.auth.login.LoginException: Provided token was null or empty!
        at net.dv8tion.jda.core.entities.impl.JDAImpl.login(JDAImpl.java:106)
        at net.dv8tion.jda.core.JDABuilder.buildAsync(JDABuilder.java:454)
        at fredboat.FredBoatClient.<init>(FredBoatClient.java:47)
        at fredboat.FredBoat.main(FredBoat.java:176)
Exception in thread "main" java.lang.NullPointerException
        at fredboat.FredBoat.main(FredBoat.java:181)

Just after:
[11:20:44] [ INFO ] [FredBoat] 1 shards have been constructed
[11:20:44] [ ERROR] [FredBoat] Failed to start JDA client

**Comment by Frederikam** [comment]
Your token is still invalid, as the error message would imply

**Comment by Hinkii** [comment]
But the bot is running and playing music properly, I've always gotten this error.

**Comment by Frederikam** [comment]
That sounds very odd. Are you sure you are not running more than one instance of the bot?

**Comment by Frederikam** [comment]
Oh wait, this is the selfbot version of the bot failing to start. This feature is deprecated and has been removed in the latest (unstable) version. You can safely ignore that.

**Comment by Hinkii** [comment]
Certain, even looking in one of my logs I guess I got a little too ambitious when queuing a link soon after launching and even see this:
[14:14:43] [ INFO ] [JDA] Finished Loading!
[14:14:43] [ INFO ] [EventLogger] [:rocket:] Received ready event.
[14:14:43] [ INFO ] [FredBoat] Received ready event for [00 / 01]
[14:14:43] [ INFO ] [FredBoat] All 1 shards are ready.
[14:14:43] [ INFO ] [MusicPersistenceHandler] Began reloading playlists
[14:14:45] [ INFO ] [EventListenerBoat] xxxxx 	 Hinki ? 	 ;;play on a tuesday
[14:14:46] [ INFO ] [GarbageCollectionMonitor] GC monitoring enabled, reporting results every 2 minutes.
[14:14:46] [ INFO ] [JDA] Audio System successfully setup!
[14:14:46] [ INFO ] [EventListenerBoat] xxxxx 	 MusicBot 	 Searching YouTube for `on a tuesday`...
[14:14:48] [ INFO ] [FredBoat] 1 shards have been constructed
[14:14:48] [ ERROR] [FredBoat] Failed to start JDA client

**Comment by Hinkii** [comment]
Is the unstable the current open release or? Because I update it nearly every time I notice a new update on the GitHub page, I dunno if that's a bad habit or not..

**Comment by Frederikam** [comment]
The master branch is stable, but the latest version is always available on the development branch. May not always build, but it should be working right now.

**Comment by Hinkii** [comment]
Okay, thank you! Sorry a little new to actually browsing and using GitHub, and thanks for the bot and it's entirety. I've referred quite a few people to it whenever they complain about downtime/waiting in a queue for more, "traditional," bots. ❤️

**Comment by Frederikam** [comment]
You're welcome! I'm glad to hear that people are enjoying my work 😄
