### ISSUE TITLE
userinfo don't work

### ISSUE THREAD

**Issue by CrazyCaferReis** [Frederikam/FredBoat#327]
I Using self host but don't work userinfo command crashing
[11:53:57] [JDA [1 / 2] MainWS-ReadThread] [TextUtils] Caught exception while executing a command
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key userinfoAvatarUrl
	at java.util.ResourceBundle.getObject(Unknown Source)
	at java.util.ResourceBundle.getString(Unknown Source)
	at fredboat.command.util.UserInfoCommand.onInvoke(UserInfoCommand.java:92)
	at fredboat.commandmeta.CommandManager.prefixCalled(CommandManager.java:141)
	at fredboat.event.EventListenerBoat.limitOrExecuteCommand(EventListenerBoat.java:134)
	at fredboat.event.EventListenerBoat.onMessageReceived(EventListenerBoat.java:110)
	at net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:402)
	at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:84)
	at net.dv8tion.jda.core.handle.MessageCreateHandler.handleDefaultMessage(MessageCreateHandler.java:128)
	at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:49)
	at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
	at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:885)
	at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:578)
	at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:260)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:238)
	at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:963)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:746)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)

**Comment by napstr** [comment]
Fixed in the development branch.

**Comment by CrazyCaferReis** [comment]
send me link ?

**Comment by napstr** [comment]
Use the link marked as "unstable" on https://fredboat.com/docs/selfhosting (yes I am aware of the irony here :D ), or wait for the next release.
