### ISSUE TITLE
FredBoat startup error

### ISSUE THREAD

**Issue by KKHaneul** [Frederikam/FredBoat#386]
```
Exception in thread "main" java.lang.RuntimeException: Failed starting database connection
        at fredboat.db.DatabaseManager.startup(DatabaseManager.java:176)
        at fredboat.FredBoat.main(FredBoat.java:142)
Caused by: org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:271)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:233)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:210)
        at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:51)
        at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:94)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:242)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:210)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.handleTypes(MetadataBuildingProcess.java:352)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:111)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:858)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:885)
        at org.hibernate.jpa.HibernatePersistenceProvider.createContainerEntityManagerFactory(HibernatePersistenceProvider.java:151)
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:353)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:370)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:359)
        at fredboat.db.DatabaseManager.startup(DatabaseManager.java:139)
        ... 1 more
Caused by: org.hibernate.HibernateException: java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:sqlite:fredboat.db
        at org.hibernate.hikaricp.internal.HikariCPConnectionProvider.configure(HikariCPConnectionProvider.java:63)
        at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:94)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:242)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:210)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.buildJdbcConnectionAccess(JdbcEnvironmentInitiator.java:145)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:66)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)
        at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:88)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:259)
        ... 16 more
Caused by: java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:sqlite:fredboat.db
        at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:88)
        at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:318)
        at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:108)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:99)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:71)
        at org.hibernate.hikaricp.internal.HikariCPConnectionProvider.configure(HikariCPConnectionProvider.java:59)
        ... 24 more
Caused by: java.sql.SQLException: No suitable driver
        at java.sql.DriverManager.getDriver(DriverManager.java:315)
        at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:81)
        ... 29 more
```
What can i do? i didn't input any char in jdbcUrl..

**Comment by KKHaneul** [comment]
No one there..? T_T

**Comment by Frederikam** [comment]
Can you post the full log?

**Comment by KKHaneul** [comment]
@Frederikam https://pastebin.com/Gi8JtKrL is the full log file.

**Comment by Frederikam** [comment]
What OS?

**Comment by KKHaneul** [comment]
I using Ubuntu 16.04.3 LTS x64.

**Comment by Frederikam** [comment]
No idea what could be causing this to be honest. Try an earlier version on master

**Comment by KKHaneul** [comment]
Well.. legacy version is working correctly. thanks..!

**Comment by KKHaneul** [comment]
@Frederikam Sorry for later message but I was wondering if you know why this error are displayed.

**Comment by napstr** [comment]
Probably due to the switch to gradle as a build system.

**Comment by napstr** [comment]
Spring/Hikari tries to autoconfigure the database driver and that fails. I've seen something similar happen in a different project. This can probably be fixed by explicitly telling the database manager which driver to use. However sqlite is about to be phased out anyways.

**Comment by KKHaneul** [comment]
Thanks.. :D

**Comment by napstr** [comment]
Actually I'm a bit surprised this is happening the way you reported it.
1. The tests include creating and running queries against sqlite. They did not fail.
2. Master was merged from development just yesterday. Either both should be failing or none.

**Comment by napstr** [comment]
Hey, this was actually an issue, and was just fixed. Both stable and unstable builds were affected, and should be working again.

**Comment by formatme** [comment]
still getting this bug

**Comment by napstr** [comment]
Download the latest jar from the stable branch.
