### ISSUE TITLE
Database Error (Selfhosting)

### ISSUE THREAD

**Issue by Chin077** [Frederikam/FredBoat#489]
So i tried to selfhost fredboat with docker, i did everything in the tutorial i read everything but if i boot it up with docker is gives this error:

> `[15:38:53] [ INFO ] [] [HikariDataSource] fredboat.main-DefaultPool - Starting...
[15:38:54] [ ERROR] [] [HikariPool] fredboat.main-DefaultPool - Exception during pool initialization.
org.postgresql.util.PSQLException: Connection to db:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:247)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
	at org.postgresql.Driver.makeConnection(Driver.java:452)
	at org.postgresql.Driver.connect(Driver.java:254)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:375)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:204)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:459)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:533)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:114)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:82)
	at space.npstr.sqlsauce.DatabaseConnection.<init>(DatabaseConnection.java:169)
	at space.npstr.sqlsauce.DatabaseConnection$Builder.build(DatabaseConnection.java:845)
	at fredboat.db.DatabaseManager.main(DatabaseManager.java:93)
	at fredboat.main.Launcher.main(Launcher.java:110)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.postgresql.core.PGStream.<init>(PGStream.java:69)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:158)
	... 15 common frames omitted`

Yes i used the right bottoken,

**Comment by napstr** [comment]
This issue tracker is not the place to ask how to selfhost FredBoat. There are plenty of links in the docs to the proper place for that.
