### ISSUE TITLE
bot didn`t responding

### ISSUE THREAD

**Issue by restaw** [Frederikam/FredBoat#554]
i use self hosted bot and it worked as usual, but after restarting bot appears error if use any command

here is the log
```
[19:45:05] [ INFO ] [JDA [0 / 1] MainWS-ReadThread] [guild=519206556148039685, channel=519206556148039691, invoker=307600768570097665] [EventListenerBoat] !ping
[19:45:05] [ ERROR] [JDA [0 / 1] RateLimit-Worker 4] [] [Requester] There was an exception while executing a REST request
org.json.JSONException: JSONObject["description"] not a string.
at org.json.JSONObject.getString(JSONObject.java:810)
at net.dv8tion.jda.core.entities.EntityBuilder.createApplicationInfo(EntityBuilder.java:1289)
at net.dv8tion.jda.bot.entities.impl.JDABotImpl$1.handleResponse(JDABotImpl.java:65)
at net.dv8tion.jda.core.requests.Request.handleResponse(Request.java:184)
at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:225)
at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:133)
at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:116)
at net.dv8tion.jda.core.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:350)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
[19:45:06] [ ERROR] [JDA [0 / 1] RateLimit-Worker 4] [] [RateLimiter] Requester system encountered an internal error
java.lang.IllegalStateException: An error occurred while parsing the response for a RestAction
at net.dv8tion.jda.core.requests.Response.<init>(Response.java:74)
at net.dv8tion.jda.core.requests.Response.<init>(Response.java:50)
at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:242)
at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:133)
at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:116)
at net.dv8tion.jda.core.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:350)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException: null
at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268)
at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258)
at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
at net.dv8tion.jda.core.requests.Requester.getBody(Requester.java:295)
at net.dv8tion.jda.core.requests.Response.<init>(Response.java:70)
... 12 common frames omitted
```

**Comment by OtterBoops** [comment]
This is a self-hosting question and not actually a bug with the bot.
Head on over to https://discord.gg/cgPFW4q and ask for access to the selfhosting channel for help with getting everything set up.
