### ISSUE TITLE
"Something went wrong!" while trying to play

### ISSUE THREAD

**Issue by TurtlePU** [Frederikam/FredBoat#582]
I'm using a publicly hosted version of FredBoat.

It started yesterday or the day before yesterday. After I type `play n`, FredBoat refuses to play some tracks which played nicely before. The message is, for example,

> Something went wrong!
> Track `Liquid Drum and Bass Mix #60` failed to load. Skipping...

Is it a problem with the bot? Or some changes of YouTube API? Or something else?
The bot is nice, I don't want to replace it with some other.

**Comment by napstr** [comment]
Post logs.

**Comment by TheFrozenOne** [comment]
I am using a selfhosted bot. The bot is hosted using docker.
I've been encountering the same Problem recently.

Here are the error messages from lavalink.log and fredboat.log respectively

lavalink.log

2019-06-13 11:38:44.157 ERROR 1 --- [lava-daemon-pool-playback-5-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of ws_qgThhC40

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[lavaplayer-1.3.10.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:102) ~[lavaplayer-1.3.10.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-1.3.10.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.lang.RuntimeException: Not success status code: 403
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:86) ~[lavaplayer-1.3.10.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:115) ~[lavaplayer-1.3.10.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:104) ~[lavaplayer-1.3.10.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:149) ~[lavaplayer-1.3.10.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:165) ~[lavaplayer-1.3.10.jar!/:na]
        at java.base/java.io.DataInputStream.readByte(DataInputStream.java:270) ~[na:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39) ~[lavaplayer-1.3.10.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:46) ~[lavaplayer-1.3.10.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:79) ~[lavaplayer-1.3.10.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:51) ~[lavaplayer-1.3.10.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:34) ~[lavaplayer-1.3.10.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:27) ~[lavaplayer-1.3.10.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:75) ~[lavaplayer-1.3.10.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:67) ~[lavaplayer-1.3.10.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90) ~[lavaplayer-1.3.10.jar!/:na]
        ... 4 common frames omitted

and fredboat.log

[11:38:44] [] [WebSocketConnectReadThread-26] [AbstractPlayer] Lavaplayer encountered an exception while playing ws_qgThhC40
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Unexpected exception
        at lavalink.client.player.event.AudioEventAdapterWrapped.onEvent(AudioEventAdapterWrapped.java:55)
        at lavalink.client.player.LavalinkPlayer.lambda$emitEvent$0(LavalinkPlayer.java:208)
        at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:803)
        at lavalink.client.player.LavalinkPlayer.emitEvent(LavalinkPlayer.java:208)
        at lavalink.client.io.LavalinkSocket.handleEvent(LavalinkSocket.java:153)
        at lavalink.client.io.LavalinkSocket.onMessage(LavalinkSocket.java:95)
        at lavalink.client.io.ReusableWebSocket$DisposableSocket.onMessage(ReusableWebSocket.java:134)
        at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:462)
        at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:696)
        at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:367)
        at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:212)
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:389)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: lavalink.client.io.RemoteTrackException: Something broke when playing the track.
        at lavalink.client.io.LavalinkSocket.handleEvent(LavalinkSocket.java:129)
        ... 8 common frames omitted

**Comment by Frederikam** [comment]
I believe you are both out of date. Please update your lavalink nodes

**Comment by TheFrozenOne** [comment]
Seems to a bug with youtube api. Tried a few hours later and it worked, same bot version btw.

**Comment by Frederikam** [comment]
It is expected that YouTube will make changes to their API. It is not a bug on their end. Just update your lavalink nodes to fix the problem.

**Comment by Frederikam** [comment]
I assume this was fixed long ago

**Comment by FruitMonkey** [comment]
Hi. I've been having the same issue. Last time I used Fred successfully was two weeks ago, but since yesterday, it has been giving me the same issue. Has a solution been found?
